FROM python:3

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN mkdir flask-project

WORKDIR /flask-project
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD [ "flask", "run" ]
